# Generated by Django 3.0.2 on 2020-01-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_timeroutine_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeroutine',
            name='order',
        ),
        migrations.RemoveField(
            model_name='timesegment',
            name='position',
        ),
    ]
