# Generated by Django 3.0.2 on 2020-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0004_auto_20200126_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeroutine',
            name='order',
            field=models.CharField(default='', max_length=500),
        ),
    ]
