# Generated by Django 3.0.2 on 2020-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0005_timeroutine_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeroutine',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
    ]
